CREATE TABLE IF NOT EXISTS users(
    name VARCHAR(256) PRIMARY KEY,
    skills TEXT NOT NULL DEFAULT '',
    exp INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS vacancies(
    title VARCHAR(256) PRIMARY KEY,
    company VARCHAR(256) NOT NULL DEFAULT '',
    tags TEXT NOT NULL DEFAULT '',
    exp INT NOT NULL DEFAULT 0
);